
const linkURLS = [
    'http://www.kitka.org/wintersongsdaily/dec1'
]

const boxes = [
    {
        id: 1,
        ready: true,
        pulsing: false,
        x: 230, 
        y: 580,
        w: 140,
        h: 85,
    },
    {
        id: 2,
        ready: true,
        pulsing: false,
        
        x: 145, 
        y: 270,
        w: 50,
        h: 50,
    },
    {
        id: 3,
        ready: true,
        pulsing: true,
        x: 522, 
        y: 290,
        w: 60,
        h: 80,
    },
    {
        id: 4,
        ready: true,
        pulsing: false,
        x: 955, 
        y: 285,
        w: 45,
        h: 50,
    },
    {
        id: 5,
        ready: true,
        pulsing: false,
        x: 920, 
        y: 490,
        w: 100,
        h: 80,
    },
    {
        id: 6,
        ready: true,
        pulsing: false,
        x: 315, 
        y: 400,
        w: 80,
        h: 70,
    },
    {
        id: 7,
        ready: true,
        pulsing: false,
        x: 900, 
        y: 580,
        w: 110,
        h: 100,
    },
    {
        id: 8,
        ready: true,
        pulsing: false,
        x: 775, 
        y: 250,
        w: 40,
        h: 55,
    },
    {
        id: 9,
        ready: true,
        pulsing: false,
        x: 1130, 
        y: 555,
        w: 122,
        h: 80,
    },
    {
        id: 10,
        ready: true,
        pulsing: false,
        x: 60, 
        y: 270,
        w: 80,
        h: 80,
    },
    {
        id: 11,
        ready: true,
        pulsing: false,
        x: 1150, 
        y: 455,
        w: 120,
        h: 80,
    },
    {
        id: 12,
        ready: true,
        pulsing: false,
        x: 55, 
        y: 455,
        w: 70,
        h: 60,
    },
    {
        id: 13,
        ready: true,
        pulsing: false,
        x: 635, 
        y: 340,
        w: 100,
        h: 80,
    },
    {
        id: 14,
        ready: true,
        pulsing: false,
        x: 720, 
        y: 567,
        w: 125,
        h: 120,
    },
    {
        id: 15,
        ready: true,
        pulsing: false,
        x: 1055, 
        y: 440,
        w: 80,
        h: 80,
    },
    {
        id: 16,
        ready: true,
        pulsing: false,
        x: 1050, 
        y: 340,
        w: 110,
        h: 90,
    }
    ,
    {
        id: 17,
        ready: true,
        pulsing: false,
        x: 250, 
        y: 220,
        w: 90,
        h: 170,
    },
    {
        id: 18,
        ready: true,
        pulsing: false,
        x: 70, 
        y: 610,
        w: 150,
        h: 140,
    },
    {
        id: 19,
        ready: true,
        pulsing: false,
        x: 680, 
        y: 260,
        w: 90,
        h: 75,
    },
    {
        id: 20,
        ready: true,
        pulsing: false,
        x: 995, 
        y: 380,
        w: 51,
        h: 100,
    },
    {
        id: 21,
        ready: true,
        pulsing: false,
        x: 80, 
        y: 360,
        w: 120,
        h: 45,
    },
    {
        id: 22,
        ready: true,
        pulsing: false,
        x: 880, 
        y: 295,
        w: 60,
        h: 50,
    },
    {
        id: 23,
        ready: true,
        pulsing: false,
        x: 440, 
        y: 500,
        w: 140,
        h: 130,
    },
    {
        id: 24,
        ready: true,
        pulsing: false,
        x: 350, 
        y: 485,
        w: 65,
        h: 80,
    },
    {
        id: 25,
        ready: true,
        pulsing: false,
        x: 830, 
        y: 180,
        w: 85,
        h: 112,
    },
    {
        id: 26,
        ready: true,
        pulsing: false,
        x: 110, 
        y: 520,
        w: 100,
        h: 50,
    },
    {
        id: 27,
        ready: true,
        pulsing: false,
        x: 850, 
        y: 390,
        w: 145,
        h: 80,
    },
    {
        id: 28,
        ready: true,
        pulsing: false,
        x: 215, 
        y: 415,
        w: 95,
        h: 80,
    },
    {
        id: 29,
        ready: true,
        pulsing: false,
        x: 1130, 
        y: 270,
        w: 100,
        h: 65,
    },
    {
        id: 30,
        ready: true,
        pulsing: false,
        x: 775, 
        y: 310,
        w: 90,
        h: 65,
    },
    {
        id: 31,
        ready: true,
        pulsing: false,
        x: 610, 
        y: 460,
        w: 100,
        h: 80,
    }
];

const starOffsets = [
    {
        id: 1,
        x: 340,
        y: 620,
    },
    {
        id: 2,
        x: 170,
        y: 260,
    },
    {
        id: 3,
        x: 500,
        y: 270,
    }
];
